repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-sdk-python
        name: "Run Python checks"
        language: system
        files: ^python/
        types_or: [markdown, python]
        pass_filenames: false
        entry: make -C python pre-commit

      - id: check-sdk-typescript
        name: "Run TypeScript checks"
        language: system
        files: ^typescript/
        types_or: [javascript, ts, json, yaml]
        pass_filenames: false
        entry: npm --prefix typescript run ci-pr-check


      - id: check-cli
        name: "Run CLI checks"
        language: system
        files: ^cli/
        types_or: [javascript, ts, json, yaml]
        pass_filenames: false
        entry: npm --prefix cli run check-all